### ISSUE TITLE
Deleting a command like `/help` causes it to run again

### ISSUE THREAD

**Issue by KhudaDad414** [asyncapi/.github#110]
commands should trigger a workflow only if the comment is `created` or maybe `edited`? not if it is `deleted`. 
this issue becomes problematic especially if someone deletes the `asyncapi-bot` response for `/help`. It causes all of the commands mentioned in the `/help` response to run simultaneously.

**Comment by derberg** [comment]
@KhudaDad414 yeah, makes a lot of sense to only react on `created` IMHO, the same with `rtm` and `dnm` comments
