### ISSUE TITLE
Add `/review` to automatically add codeowners as reviewers

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/.github#112]
#### Reason/Context
With the recent introduction of the CODEOWNERS files, I often have to go and check who are the owners of a repo and then add them to review my PR. It would be awesome to have a slash command that does this for you.

#### Description
Add a new slash command: `/review`. This command will trigger a Github action that will read the CODEOWNERS file (if present) and add the listed users as reviewers of a PR.

**Bonus**

Some people are code owners of just some directories or files in a repo. It would be superb if the action checks the changed files in a repo and add only those affected code owners.

Example: https://github.com/asyncapi/website/blob/master/CODEOWNERS#L11

Alejandra is only a code owner of Markdown files. With this command, she shouldn't be added as a reviewer if no Markdown files have been changed. This will prevent her inbox from being flooded with useless notifications.

**Comment by derberg** [comment]
This is super weird. I can bet some money that in the past this is how CODEOWNERS worked. That GitHub did an automated assignment, checking the scope of the code ownership. 

This is why in @KhudaDad414 issue about TSC voting I said that better to do voting on PR as we could get TSC members automatically assigned 🤔 


https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
![Screenshot 2021-12-17 at 10 36 28](https://user-images.githubusercontent.com/6995927/146523110-c8ee628f-d427-4b0d-b7d0-9019ef300a27.png)


GitHub bug?

**Comment by fmvilas** [comment]
Oh, I had no idea. I don't think I've ever seen it working like this for me.

**Comment by derberg** [comment]
I created this https://github.community/t/auto-assignment-with-codeowners-doesnt-work/218560

Let's give them a week or two to answer and then we are sure if we want to work on such workflow. There are some actions in the marketplace that we could use so not much work should be needed

**Comment by fmvilas** [comment]
Thanks for creating the issue on their side 👍

**Comment by derberg** [comment]
ok, looks like auto assignment that should work, did not work because we had errors in CODEOWNERS files. 
We need to start using additional bot https://github.com/asyncapi-bot-eve to accept work submitted by `asyncapi-bot`
