### ISSUE TITLE
PR owner can't see "branch out of date with master" notice after `/rtm`

### ISSUE THREAD

**Issue by mcturco** [asyncapi/.github#115]
#### Describe the bug
When adding `/rtm` on my approved PR, the expected behavior is for GH bot to automatically rebase the branch with the master version. Either way, even though the PR branch was out of date, the PR owner should be able to see a notice of that even when they aren't a codeowner. 

Here's the only notice that I saw:
![Screen Shot 2022-01-03 at 11 34 23 AM](https://user-images.githubusercontent.com/60163079/147958790-3738b74e-fe37-42c0-91fd-344a5e2bf2e1.png)

From @derberg:
"we need to think about fix as there are 2 ways to fix it, bot can do update with master or bot can just provide a comment feature like /rtm so anyone can trigger merge….not sure if the first solution will be accepted by all

we do autoupdates already but only in PRs created by bot, as nobody cares about bot’s feelings (this is why robots will kill all humans one day :smile: )

https://github.com/asyncapi/website/pull/526 notice that github bot updated branch with latest master"

**Comment by derberg** [comment]
more context on why not being up to date with master blocks merge, we have such setting everywhere 👇🏼 

![Screenshot 2022-01-03 at 18 10 57](https://user-images.githubusercontent.com/6995927/147959188-8a9057fc-eb54-40e2-93a2-a618c3a8b9a0.png)

This is a best practice. One way to skip this setting and resolve this problem the other way around is that our testing pipelines should be designed in the way, that when they run, they first rebase with master (to testing always happens with latest changes from master), and they are simply triggered on any merge to master.

not sure what is the best solution really. I think we should pick the one that is least heavy for the CI (to not overload it) and doesn't matter how complicated it will be to achieve it.

**Comment by derberg** [comment]
This is what people with write access to the repo see

![Screenshot 2022-01-03 at 17 13 37](https://user-images.githubusercontent.com/6995927/147959692-59f4df6b-b6cb-4598-9679-77768a4d8ad9.png)

**Comment by KhudaDad414** [comment]
I think the first option, having a command like `/rebase` would be less heavy on CI and provide a way for non-code-owners to rebase. plus, adding a comment like `This branch is out-of-date with the base branch, you can use /rebase to update this branch.` from `/rtm` if it fails due to out-of-date branch maybe?
