### ISSUE TITLE
Create custom github action that picks the change in workflow files and populates the change to all other repositories

### ISSUE THREAD

**Issue by derberg** [asyncapi/.github#12]
#### Reason/Context
- GitHub Actions do not support "global" GitHub Actions (yeap, true). 
- We have many workflows that are exactly the same across all repositories. If there is a need to change something in one, we need to go to these 30-something repos and make a change, manually.....omg

#### Description

Create an action that populates changes automatically for us:
- `.github` repo is a global repo for us, with global workflows that need to be populated to all other repositories
- we change workflow, like welcome workflow, in `.github` repo and review it here
- we merge the change and action comes into play
- action picks up that change in workflow was done
  - it clones all repos
  - updates the same workflow file in every repo
  - creates new branch with change and creates pull request
  - automerge workflow in every repo automatically approves and merges PR as it comes from asyncapi-bot
- puppies get crazy of happiness 
Please try answering few of those questions
- What changes have to be introduced?
- Will this be a breaking change?
- How could it be implemented/designed?

**Comment by lukasz-lab** [comment]
Initial idea visualized

![diagram](https://user-images.githubusercontent.com/15824750/99685970-6cd65400-2a83-11eb-8c4a-6363810c0000.png)
