### ISSUE TITLE
Run Workflows on Label

### ISSUE THREAD

**Issue by imabp** [asyncapi/.github#126]
#### Reason/Context
Please try answering few of those questions
- Why we need this improvement?
Maintainers have to run the workflow everytime manually, whenever new changes are added in PR.
- How will this change help?
This will save maintainer's time.

#### Description
Please try answering few of those questions
- What changes have to be introduced?
     - Maintainer can add label named `workflow-granted` or `workflow-run` 
     - This will trigger workflow runs automatically.
     - So for existing PRs which have new changes, maintainer need not run workflows manually. 
 
- Will this be a breaking change?
Nope

- How could it be implemented/designed?
We possibly need to make a github action on this. And do some brainstorming about the real flow, as it includes sensitive data handling.

**Comment by derberg** [comment]
@imabp just to make sure, did you check if GH API enables you to approve workflow runs with API

**Comment by imabp** [comment]
I have gone through this documentation.
We can listen to the addition of label, and trigger the workflow..
I will try to do a dry run locally.. Before sending a PR.
https://docs.github.com/en/actions/using-workflows/triggering-a-workflow

**Comment by derberg** [comment]
I would treat it as last possible solution, as it will be hard to figure out per repo which workflows to trigger I think. API would be best, but if supported of course :)

**Comment by derberg** [comment]
there is a long thread of ideas [here](https://github.community/t/how-to-auto-approve-workflow-runs-for-first-time-contributors/176436/15), maybe you find something

**Comment by imabp** [comment]
@derberg I got another article, as an workaround of what we are looking for [here](https://github.community/t/do-something-if-a-particular-label-is-set/17149)

**Comment by imabp** [comment]
@derberg  on above context, I found the workaround for enabling this.
But I am stuck in finding the workflow runner files. 
We need to add this it to our main runner jobs.

```yaml 
if: contains(github.event.pull_request.labels.*.name, 'workflow-run')
```

**Comment by derberg** [comment]
we have our bot there with its token enabled for all repos, so this is not a problem. My only question is what we do with it. How technically we tell GH to actually run the workflows. Label is just a "condition"

**Comment by imabp** [comment]
@derberg , I was going through all of this. 
😔 Unfortunately, we cannot do this yet, as GitHub doesn't allow it.  

Apologies, for taking so much time on figuring it out. 
I will close this issue and narrow down the focus to more productive contributions 🙂

**Comment by derberg** [comment]
no worries mate, it is good to from time to time check if something did not improve 👍🏼
