### ISSUE TITLE
Skip `Welcome first time contributers`, `Sentiment Analysis` and `Lint PR title` for bots

### ISSUE THREAD

**Issue by KhudaDad414** [asyncapi/.github#129]
#### Reason/Context
I have been trying to find areas where we can improve our CI/CD pipelines and this seems like the best place to start.

#### Description
These three workflows (or maybe others) only apply to humans and by skipping these workflows in case the author is one of our trusted bots, we can get more out of GitHub Actions.

**Comment by derberg** [comment]
yup, makes a lot of sense 👍🏼
