### ISSUE TITLE
Workflow does not need to run when PR is a draft 

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/.github#13]
#### Reason/Context
Same reasons as in https://github.com/asyncapi/parser-js/issues/200 we should disable `sentiment-analysis.yml` and `automerge.yml`. It does not make sense to run it whena PR is in draft mode.

#### Description
Add `if: github.event.pull_request.draft == false` check and ensure `ready_for_review` **on** type are added otherwise when a draft becomes ready to review it wont trigger the job.

**Comment by derberg** [comment]
I think for sentiment analysis we should monitor from start, as text can be negative before it is submitted for review
