### ISSUE TITLE
Skip PR testing early

### ISSUE THREAD

**Issue by KhudaDad414** [asyncapi/.github#130]
#### Reason/Context
We have two workflows for testing,  `PR testing - if Go project` and `PR testing - if Node project`. they are our most resource-consuming workflows. after merging  #129 we will ignore tests for some PRs but I think we can push it further by skipping the workflow entirely if it is not in the appropriate repo.

#### Description
We can maintain an ignore repo list for each workflow, and skip the workflow early if the current repo is in that list.

**Comment by derberg** [comment]
Back in the time when I was designing these workflows my initial idea was to "skip" these node-only or go-only with `topics`
So basically if you do not have `go` topic in the repo, go workflows are skipped, and the same with node. This would enable the highest flexibility. But at that time, I did not have access to `topic` info, but maybe it has changed

also I was always thinking that we could extend `global-workflows` action with some config of some sort where you expecify that Workflow A will be copied only to repos with label A.

**Comment by KhudaDad414** [comment]
I see we don't have access to `topics` in GitHub Actions context yet. extending `global-workflows` seems like a good approach.

**Comment by derberg** [comment]
> I see we don't have access to topics in GitHub Actions context yet 

that sucks like a lot...

> extending global-workflows seems like a good approach.

😅

**Comment by derberg** [comment]
while working on my latest PR, while debugging and checking events payload, I noticed that `repository` object is always there, even if workflow was triggered by issue_comment or new discussion. Of course something to confirm with docs but looks like below should work:

```
contains(github.event.repository.topics, 'nodejs')
```

**Comment by KhudaDad414** [comment]
I see. So all we have to do is add the topics to all the repos and add an `if` statement to the tests. the only thing that is remaining is deciding what to do with repos that are not `node` nor `go` like https://github.com/asyncapi/spec.

**Comment by derberg** [comment]
yeah, first better check somewhere if my idea works 😄 

and yeah, regarding `spec` and others, they will just have their individual test workflows, not global as they are probably more "specific". We have situation in few repost where global test PR workflow runs + there are additional local custom PR testing workflows (like ts code generator for example)

**Comment by KhudaDad414** [comment]
@derberg I checked and the idea works. but I am still a fan of the "smart distribution" of workflows using `global-workflows` action. like: only include `if-nodejs-pr-testing.yml` if the repo has a `nodejs` topic. it would really help control what goes where instead of sending workflows blindly to the repos.

**Comment by derberg** [comment]
@KhudaDad414 yeap, I agree. Next week I'm off on holiday and then a week after I'm off to do some work on side projects, so will use this time also to put more love into `global-workflows`.

Lemme know beforehand what would be the best way to handle such configuration. I see 2 options:
- separate yaml file that you keep in repo and in the workflow you just provide path to the config file
- in workflow you have config property that can be a multiline string, `worflowFileName.yml:topicName`

Or just both? + logic that if I add some file to the config, and specify topic, then workflow will also handle removal of the workflow files that are already in repos that do not have a given topic?

**Comment by KhudaDad414** [comment]
@derberg I think having a config file seems like a great idea since it may grow large. It would be cool if we have the option to move the current configurations of the action in that file as well.

> logic that if I add some file to the config, and specify topic, then workflow will also handle removal of the workflow files that are already in repos that do not have a given topic?

this is great but we should be able to turn this feature off in the configuration.

to ease the process I think we should be able to configure the opposite as well. like: ignore `if-nodejs-pr-testing.yml` if the repo has a `go` topic. this way, the repos that don't follow the convention of adding the specific topic, will get both `if-nodejs-pr-testing.yml` and `if-go-pr-testing.yml`.

**Comment by KhudaDad414** [comment]
another cool thing that we could do with this feature would be to have a topic like `no-global-testing` and that repo will recieve no testing workflow at all. and they can add their own workflows for testing :smile: 🤩

**Comment by derberg** [comment]
@KhudaDad414 I think we can close it, and now we just need to open 50-like issues in all repos to cleanup the workflow files from these

**Comment by derberg** [comment]
Update:

still valid
global workflow optimized to not push all workflows to all repos in dummy way, but now it does it under certain conditions
we just now need to open issues in all repos to do cleanup

so in case of nodejs projects, go related workflows should be removed
and in case of go projects, nodejs related workflows should be removed

**Comment by derberg** [comment]
@KhudaDad414 closing this one as my lovely wife cleaned up all the repos from irrelevant workflows 💪🏼 
55PRs 🚀  -> https://github.com/pulls?q=is%3Apr+author%3Acodingtenshi+sort%3Acreated-asc+

**Comment by KhudaDad414** [comment]
thanks a lot, @codingtenshi. 🙇  I hope you did it all by choice and @derberg is not keeping you hostage somewhere. if that's the case give us a sign. we can call the police or something. 😟

**Comment by codingtenshi** [comment]
> thanks a lot, @codingtenshi. 🙇 I hope you did it all by choice and @derberg is not keeping you hostage somewhere. if that's the case give us a sign. we can call the police or something. 😆

:) It was my choice, everything is all right. Thanks for your concern :)
