### ISSUE TITLE
Update README with new logo banner

### ISSUE THREAD

**Issue by mcturco** [asyncapi/.github#144]
#### Reason/Context
This is to replace the old AsyncAPI logo in this repo's README with the banner attached below that represents the new branding.

**Here are a few guidelines for this change as well:**
1. Make sure you are using [Markdown syntax](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) only
2. Be sure to remove the old logo as well as the old title of the repo as this image will replace both elements
3. Make sure you link this image to the website: `https://www.asyncapi.com`
4. If there is any description text below the repo title, let's make it left-aligned if it isn't already, so as to match the left-alignment of the content in the new banner image

**Download the image file:**
[github-repobanner-ghcommunityhealth.png.zip](https://github.com/asyncapi/.github/files/8232790/github-repobanner-ghcommunityhealth.png.zip)

------

#### Banner preview
_Please note that this is only a preview of the image, the contributor should download and use the above zip file_ 

<img width="830" alt="github-repobanner-ghcommunityhealth" src="https://user-images.githubusercontent.com/60163079/157888261-9191a6a6-4072-497d-80a3-8695a1cb5fe5.png">

**Comment by aniketh-varma** [comment]
Hi @mcturco, I would like to work on this issue. I am a part of OpenForce 2022.

**Comment by mcturco** [comment]
Hi @aniketh-varma! 👋 
Thank you! Go ahead with this one, I am unable to assign this to you in GH due to permissions but go ahead with the PR 👍
