### ISSUE TITLE
Validate workflow on PR level

### ISSUE THREAD

**Issue by KhudaDad414** [asyncapi/.github#150]
#### Reason/Context
Since we don't validate our workflow files at the PR level, there is no way for us to make sure that the workflow files are valid YAML files.

#### Description
We need a linter as a workflow to make sure our workflows are valid YAML files.
BONUS: if the workflow is able to validate against the [workflow schema](https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json) it would be much better.

**Comment by Namyalg** [comment]
I am interested to work on this issue
My understanding of this issue is : 
- Create a workflow to check if new workflow files are valid and error-free using a linter

**Comment by derberg** [comment]
exactly, additionally workflow should only run if changes are done to files under `.github/workflows` directory.

regarding validation against schema, have a look at https://github.com/asyncapi/community/blob/master/.github/workflows/validate-tsc-members.yml#L19 where I already did something similar using `Ajv`. You will just have to fetch schema from remote first, instead of storing it in the repo and reading as file

**Comment by Namyalg** [comment]
Thank you for the reference, I'll get started on the implementation

**Comment by Namyalg** [comment]
I plan to use the action https://github.com/tj-actions/changed-files, which will detect the addition or modification of a file.
Once the list files are obtained, the files with .yml are run against the schema validator.

**Comment by derberg** [comment]
sounds good 👍🏼

**Comment by Namyalg** [comment]
@KhudaDad414 , is this [workflow schema](https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json) the correct one ?
It doesnt seem to follow the exact format of the yml files written for GHA

**Comment by KhudaDad414** [comment]
@Namyalg I am fairly sure that this is the schema.
Are there any issues when you validate workflows?
I tried a few of the workflows and they seem to validate fine.

**Comment by Namyalg** [comment]
Yes, this is what I get when I validate the [linkcheck workflow](https://github.com/asyncapi/.github/blob/master/.github/workflows/link-check-cron.yml)
![image](https://user-images.githubusercontent.com/53875297/164689432-2e02aed8-368c-46c4-88de-874ad4cc745c.png)

**Comment by KhudaDad414** [comment]
@Namyalg I suggest validating the file with the approach that @derberg mentioned here: https://github.com/asyncapi/.github/issues/150#issuecomment-1088445829

I tested it with this code and it works like a charm:
😃 
```js
const Ajv = require('ajv');
const axios = require('axios');
const yaml = require('js-yaml');
const fs = require('fs').promises;

const schema = await axios.get(
  'https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json'
);

const file = await fs.readFile('target.yml', 'utf8');
const target = yaml.load(file);

const ajv = new Ajv({ strict: false, allErrors: true });
const validator = ajv.compile(schema.data);
const valid = validator(target);
if (!valid) {
  console.error(`Validation failed with the following errors:`);
  console.error(validator.errors);
} else {
  console.log(`TSC members file is valid`);
}

```

**Comment by Namyalg** [comment]
Alright, will try this

**Comment by derberg** [comment]
this one is already implemented by @14Richa
