### ISSUE TITLE
ci: need to replicate COC.md to all repos

### ISSUE THREAD

**Issue by aminoxix** [asyncapi/.github#167]
#### Describe the bug

 Failed GitHub Actions in [Code of Conduct section](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md#code-of-conduct) in [CONTRIBUTING.md](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

#### How to Reproduce

- Click on `read the full text` in COC section of `CONTRIBUTING.md`
- Note: Take reference from `server-api` repo., [click here](https://github.com/asyncapi/server-api/blob/master/CODE_OF_CONDUCT.md)

#### Screenshots

![image](https://user-images.githubusercontent.com/75872316/168464533-07ec232f-9d7a-42a4-8744-4d1af09257f0.png)

#### Expected behaviour

Need to update the link in the `.github` repo, so it gets updated for other repositories in the next commit made by the `asyncapi-bot-eve`.

**Comment by aminoxix** [comment]
@derberg: Kindly review this issue, would like to take it up! :slightly_smiling_face:

**Comment by derberg** [comment]
also would be awesome if you could add to https://github.com/asyncapi/.github/blob/master/.github/workflows/global-replicator.yml file the following line: `repos_to_ignore: shape-up-process,glee-hello-world`, between line 30 and 31

**Comment by aminoxix** [comment]
> also would be awesome if you could add to https://github.com/asyncapi/.github/blob/master/.github/workflows/global-replicator.yml file the following line: `repos_to_ignore: shape-up-process,glee-hello-world`, between line 30 and 31

Changes done & also restructured action `.yml` file here: #168
