### ISSUE TITLE
we should add some custom filter to release workflow

### ISSUE THREAD

**Issue by derberg** [asyncapi/.github#184]
#### Reason/Context

Release https://github.com/asyncapi/.github/blob/master/.github/workflows/if-nodejs-release.yml relies on `semantic-release` to answer if release is needed.

This means, on every single commit it runs tests, and then release just to realize at the very end that it was not needed.

Bit waste of resources!

#### Description

I think we need to make it skip early all jobs if we notice that PR title is different than `feat`, `fix`, `feat!`

what we loose: sometimes (1% of cases) it happens that some releases of features fail, and that another `chore` commit fixes it, as release runs cause semantic release discovers unreleased feature. It will obviously no longer work as semantic-release will not ever run with this new solution

Thoughts?

**Comment by smoya** [comment]
+1 to run **only** if the current commit has any of those prefixes (`feat`, `fix`, `feat!`).

> what we loose: sometimes (1% of cases) it happens that some releases of features fail, and that another chore commit fixes it, as release runs cause semantic release discovers unreleased feature. It will obviously no longer work as semantic-release will not ever run with this new solution

If that means we will need to add an extra commit with those prefixes in order to run the release, I'm fine to be honest.
