### ISSUE TITLE
Testing workflow could skip earlier

### ISSUE THREAD

**Issue by derberg** [asyncapi/.github#200]
EDIT, only step 2 is in scope

1. I can't remember why we have [this if statement](https://github.com/asyncapi/.github/blob/master/.github/workflows/if-nodejs-pr-testing.yml#L19) on step and not job level 🤔 We could move it to job level IMHO and therefore workflow would never run - CLARIFIED - out of scope
2. go and nodejs testing workflow could be updated with more "cancel" conditions. In the case of PRs related to workflows updates, now there are more commit messages that we should consider as skippable -> https://github.com/asyncapi/.github/blob/master/.github/workflows/global-replicator.yml, not only `ci: update global workflows`

@KhudaDad414 what do you think about the 1st one?

**Comment by derberg** [comment]
@KhudaDad414 pingy pongy

**Comment by KhudaDad414** [comment]
@derberg If we move the whole condition to the job level, the tests are going to be skipped and since we have branch protection, the bot won't be able to merge it.
The only condition that can be moved safely to the job level is `github.event.pull_request.draft == false` since drafts do not need to be merged.

**Comment by KhudaDad414** [comment]
this guy explains it better https://github.com/asyncapi/.github/issues/116#issuecomment-1031752785 😆

**Comment by derberg** [comment]
> this guy explains it better https://github.com/asyncapi/.github/issues/116#issuecomment-1031752785 😆

oh shit 😆 thanks for the pointer, this guy is brilliant 🤣 

I'll mark it as a `gfi`

**Comment by arunavabasu-03** [comment]
this issue is Open ??

**Comment by derberg** [comment]
@arunavabasu-03 sure, but please read the description, point 1 should not be implemented and in the PR that you created you did only point 1 instead of 2

**Comment by dante381** [comment]
Can I work on this issue? For step 2 should i modify the commit messages in [global-replicator.yml](https://github.com/asyncapi/.github/blob/master/.github/workflows/global-replicator.yml) and could you explain the "cancel" condition for nodejs workflows?

**Comment by KhudaDad414** [comment]
@dante381 All yours. 😀

**Comment by derberg** [comment]
@dante381 step 2, what needs to be done is these workflows:
- https://github.com/asyncapi/.github/blob/master/.github/workflows/if-nodejs-pr-testing.yml
- https://github.com/asyncapi/.github/blob/master/.github/workflows/if-go-pr-testing.yml
- https://github.com/asyncapi/.github/blob/master/.github/workflows/if-docker-pr-testing.yml

whenever you see `if` statement and `startsWith(github.event.pull_request.title, 'ci: update global workflows'))` this means that given statement needs to be extended, and we should ignore not only PRs with title `ci: update global workflows` but all the other titles that you can see in https://github.com/asyncapi/.github/blob/master/.github/workflows/global-replicator.yml (you find these under `commit_message` properties). To be honest  `ci: update global workflows` is not even there anymore 😄 

Lemme know if you need more help

**Comment by dante381** [comment]
Thank you @derberg

**Comment by dante381** [comment]
`      - if: "github.event.pull_request.draft == false &&!((github.actor == 'asyncapi-bot' && startsWith(github.event.pull_request.title, 'ci: update global workflows')) || (github.actor == 'asyncapi-bot' && startsWith(github.event.pull_request.title, 'chore: update code of conduct')) || github.actor == 'asyncapi-bot' && startsWith(github.event.pull_request.title, 'ci: update global contribution guide') || github.actor == 'asyncapi-bot' && startsWith(github.event.pull_request.title, 'ci: update workflows for go projects') || github.actor == 'asyncapi-bot' && startsWith(github.event.pull_request.title, 'ci: update workflows for nodejs projects') || github.actor == 'asyncapi-bot' && startsWith(github.event.pull_request.title, 'ci: update release-related workflows for nodejs projects') || github.actor == 'asyncapi-bot' && startsWith(github.event.pull_request.title, 'ci: update semantic release config file') || github.actor == 'asyncapi-bot' && startsWith(github.event.pull_request.title, 'ci: update generic workflows') || github.actor == 'asyncapi-bot' && startsWith(github.event.pull_request.title, 'ci: update workflows for docker-based projects') || (github.actor == 'asyncapi-bot' && startsWith(github.event.pull_request.title, 'chore(release):')) || (github.actor == 'allcontributors' && startsWith(github.event.pull_request.title, 'docs: add')))"`

@derberg Could you confirm that i am going in the right direction? Is this what is to be done?
Sorry I am new to this topic.
Thank you

**Comment by derberg** [comment]
omg reading these `if` statements in GitHub workflows is like

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNzczOGE1YWExNzRlMDNhYmZlOTdmM2QyNzQ4MzUzNWYwM2Y0N2M1YiZjdD1n/ALtzQ6CHfC7vO5nRz7/giphy-downsized.gif)

@KhudaDad414 since you are an `if` statements expert 😄 any tips?

**Comment by dante381** [comment]
Thank you for your guidance @derberg  and @KhudaDad414
