### ISSUE TITLE
improve `/gfi` bot messages

### ISSUE THREAD

**Issue by derberg** [asyncapi/.github#201]
bot told me https://github.com/asyncapi/generator/issues/873#issuecomment-1333748449

but I was confused as I was sure I did it right.

I remember bot was supposed to handle usage of `/gfi` anywhere in the comment, thus `contains` and not `startsWith` used in the workflow. But code is not able to handle that use case

I do not have strong feelings for ☝🏼 

so we:
- either fix code
- or change to `startsWith` and update workflow to throw proper error to user, in case they mix

@KhudaDad414 thoughts?

**Comment by derberg** [comment]
@KhudaDad414 pingi pongi

**Comment by KhudaDad414** [comment]
I guess the code should be able to handle it anywhere. I see the problem. Will open a PR to handle it.

**Comment by alequetzalli** [comment]
what does `/gfi` stand for? 😄✌🏽

**Comment by Amzani** [comment]
@alequetzalli I guess it's to add a "good first issue" label
