### ISSUE TITLE
We need another command for PRs which acts as re-request for review and also reminder for codeowners

### ISSUE THREAD

**Issue by derberg** [asyncapi/.github#211]
We have cases like https://github.com/asyncapi/spec/pull/847#pullrequestreview-1331087602 when PR owner has hard time:
- pinging codeowners that did not yet perform any review on PR
- re-requesting review from people that already did a review, but the native re-request button feature in side bar do not work well

So we have already commands like, `ready-to-merge` or `autoupdate`. We should have more:
- `ping-for-attention`
- `rerequest`

quick proposals ☝🏼 that of course can be changed

---
before we talk about how to parse `codeowners` file, and then get data needed for requesting review, I suggest someone first check GitHub GraphQL or REST APIs as I think one day when I was exploring it, there was some API, probably GitHub Graphql mutation to trigger re-request review.

also maybe there are ready GitHub actions that we could use in workflows and there is no need to call API manually 🤔

**Comment by arunavabasu-03** [comment]
@derberg can I work on this ??

**Comment by Priyansh61** [comment]
Hey @derberg,
I would like to work on this issue. And the PR will be ready by the end of the week.

Thanks

**Comment by Priyansh61** [comment]
Hi @derberg ,

I was exploring this feature and I just had certain doubts. Like for re-request we already have an option to call from the right-top 

![image](https://github.com/asyncapi/.github/assets/96513964/7deb1c23-be71-4b68-91a7-99ffefc924f8)

And for the ping-for-attention do we want a button which serves the same purpose as (@xyz)?

Thanks,

**Comment by derberg** [comment]
nice example of comment command used in practice -> https://github.com/asyncapi/website/issues/1684#issuecomment-1551521659

**Comment by Priyansh61** [comment]
@derberg PTAL at the PR.

I had a doubt before proceeding for the PR of `rerequest`.

I went through the documentation of Github GraphQL and yes there is a mutation already present to request review https://docs.github.com/en/graphql/reference/mutations#requestreviews but we dont have any existing mutation for re-request review.

So when the user enters `/rerequest`. What should be the behaviour? 

I am thinking that the user should provide from whom he wants the review (@)  and then use `/rerequest', this way we can directly use the Github GtraphQL mutation present, and ask the specified the reviewer.

Thanks

**Comment by derberg** [comment]
looks like review works like re-review too

I did

```
mutation { 
  requestReviews(input: {pullRequestId:"PR_kwDODyzcIc5Q0XEr", userIds:"U_kgDOAGq_1w"}) {
    clientMutationId,
    pullRequest {
      id
    }
    actor {
      login
    }
  } 
}
```

where `U_kgDOAGq_1w` is my user ID, and `PR_kwDODyzcIc5Q0XEr` is ID of [this PR](https://github.com/asyncapi/.github/pull/239#pullrequestreview-1436173973)

after I fired this mutation, I noticed

<img width="1068" alt="Screenshot 2023-05-22 at 11 19 45" src="https://github.com/asyncapi/.github/assets/6995927/a8bfd6d3-076b-4fb1-bc93-f0e521d2b0e9">

so `/rereview` should work this way:
- query for IDs of current PR reviewers
- mutation to request review from these IDs. Looking at docs, `userIds` can be an array of IDs, so one mutation to request all

**Comment by Priyansh61** [comment]
> query for IDs of current PR reviewers
mutation to request review from these IDs. Looking at docs, userIds can be an array of IDs, so one mutation to request all

@derberg I just had a doubt like consider a scenario when a reviewer had already approved a PR, but some other reviewer has requested changes on it. So should we ask all the reviewers for a review?

Instead, we can have a better option that we can ask a particular person to review the PR again by having a comment @xyz @abc  /review. This way we wont disturb other reviewers and can only ask from specific users.

What's your opinion on this ?

**Comment by derberg** [comment]
contributor do not respond so this issue is still available

many things done already in https://github.com/asyncapi/.github/pull/243 so you can continue the work that was started
