### ISSUE TITLE
Try to improve autoupdate

### ISSUE THREAD

**Issue by derberg** [asyncapi/.github#227]
#### Reason/Context

The [autoupdate workflow](https://github.com/asyncapi/.github/blob/master/.github/workflows/autoupdate.yml) doesn't work with forks. 

It can update only branches that are in the upstream.

#### Description

When the branch from the fork is out of sync with master, in the UI maintainers see a button that they can click to update the branch with master.

We should allow anyone to be able to trigger such an update.

If there is a button, there needs to be API behind it, REST or GraphQL. There needs to be a research on how to trigger such branch update in form with an API. Then we need to update autoupdate workflow

**Comment by Shurtu-gal** [comment]
@derberg  Can I work upon this?

**Comment by derberg** [comment]
sure, go ahead

**Comment by Shurtu-gal** [comment]
- Should the updation of branch be automatic or manual?
 - Also anyone includes everyone or some specific group of people?
 - What should be done in case of merge conflicts?

**Comment by derberg** [comment]
- it should be manual, like use should pass come comment into PR, like `/update`
- anyone
- I think there is already a workflow that detects that where merge conflict is in place, and someone attempts to merge, bot drops a message about it. So basically extend this workflow to be triggered/used in case somebody do `/update` but it fails because of merge conflict

**Comment by Shurtu-gal** [comment]
@derberg, can you please tell me the secrets stored in the repo so that I can introduce them into the code?

Also, the updation of forks requires a maintainer level of access, if I am not wrong. 😓

**Comment by derberg** [comment]
sorry, was out on holidays

yeah, I cannot give you secrets, this is why these are secrets 😛 

> Also, the updation of forks requires a maintainer level of access, if I am not wrong

yes, and our bots are maintainers in all repos, so that will work

**Comment by derberg** [comment]
you probably need to setup alternative test account to test it. I do it on my own too, have 2 GH accounts, one that you see here and the other purely for testing
