### ISSUE TITLE
I think there is a potential bug in release pipeline

### ISSUE THREAD

**Issue by derberg** [asyncapi/.github#237]
#### Describe the bug

Before triggering a release we install a release related package -> https://github.com/asyncapi/spec-json-schemas/blob/master/.github/workflows/if-nodejs-release.yml#L104

```
run: npm install conventional-changelog-conventionalcommits@5.0.0
```

This means that whatever we push to npm, contains `conventional-changelog-conventionalcommits` which is completely irrelevant for any package

#### Expected behaviour

now I'm not sure if below is the right solution
```
run: npm install --save-dev conventional-changelog-conventionalcommits@5.0.0
```

if it is `devDependency` will it not be included in the package? I think `npm publish` will include it. 

dunno what is the solution really

**Comment by Shurtu-gal** [comment]
@derberg By adding the --save-dev flag, the package will be installed as a devDependency in your project's package.json file. DevDependencies are used for development purposes and are not included when publishing the package to npm.

But we will have to either :-
 - do uninstall and then install as devDependency
 - or just change package.json

**Comment by derberg** [comment]
we perform manual installation inside workflow https://github.com/asyncapi/spec-json-schemas/blob/master/.github/workflows/if-nodejs-release.yml#L104

so solution is just to modify this step
