### ISSUE TITLE
new global workflow for docs update

### ISSUE THREAD

**Issue by derberg** [asyncapi/.github#242]
#### Reason/Context

we have https://github.com/asyncapi/parser-js/blob/master/.github/workflows/update-docs-on-docs-commits.yml already in parser, generator and soon in cli

so it is right time to manage the workflow for this repo and then push to the ones that opt-in

#### Description

- add https://github.com/asyncapi/parser-js/blob/master/.github/workflows/update-docs-on-docs-commits.yml in this repo
  - the same file name
  - content:
      - update to use latest node v3 and 18
      - `if: startsWith(github.event.commits[0].message, 'docs:')` can be moved to job level, not step level imhp
- in global workflow provide configuration that this workflow will be updated in repos with topic `update-docs-on-docs-commits`. Would be great if you have a better name 😄

**Comment by Shurtu-gal** [comment]
Actually @kaushik-rishi I am already working on this if it's fine with you ☺️

**Comment by Shurtu-gal** [comment]
Actually I am already working on this @kaushik-rishi if it's fine with you ☺️

**Comment by kaushik-rishi** [comment]
> Actually I am already working on this @kaushik-rishi if it's fine with you relaxed

I'll work on this may be, i havent worked with actions for a while. i'll take help if i need.

**Comment by kaushik-rishi** [comment]
> Sure @kaushik-rishi

Thank you. I'm sure i'll need help. :smile:

**Comment by kaushik-rishi** [comment]
I'm working on it. :slightly_smiling_face:

**Comment by derberg** [comment]
@kaushik-rishi do you plan to continue working on this one?

**Comment by derberg** [comment]
more places where it will be used:
- https://github.com/asyncapi/java-template/blob/master/.github/workflows/update-docs-on-docs-commits.yml

**Comment by KhudaDad414** [comment]
@Shurtu-gal since @kaushik-rishi is unresponsive, do you want to work on this?

**Comment by Shurtu-gal** [comment]
> @Shurtu-gal since @kaushik-rishi is unresponsive, do you want to work on this?
Sure

**Comment by Shurtu-gal** [comment]
@derberg Is the topic autogenerate-docs fine or should I change it 🙄

**Comment by derberg** [comment]
@Shurtu-gal I'll leave comment in PR. Basically we should be consistent with topics names
