### ISSUE TITLE
support custom release processes

### ISSUE THREAD

**Issue by KhudaDad414** [asyncapi/.github#245]
#### Reason/Context
Following the conversion of the Studio repository into a monorepo via [this PR](https://github.com/asyncapi/studio/pull/638), Studio might forego using `semantic-release` for its release process. Instead, it may require its own unique logic for releasing packages.

This brings to light the necessity for a generic node release process and a new repository topic. This process should trigger `npm run release`, allowing the project to implement its specific release process.

#### Description
To address this, we can introduce another topic, which we'll refer to as `node-custom-release` for the time being. Repositories that adopt this topic will control their individual release procedures by integrating a `release` script within their `package.json` (similar to what was done before [this PR](https://github.com/asyncapi/.github/pull/204)).

In terms of workflow logic, we have two possible strategies:

1) Create a new workflow and distribute it exclusively to repositories that feature the `node-custom-release` topic, as opposed to `if-nodejs-release.yml`.

2) Append an additional step to the `if-nodejs-release.yml` process. This step would check for the `node-custom-release` topic and execute `npm run release` instead of initiating `semantic-release`. This modification would allow repositories to customize their release process whilst staying within the bounds of the existing workflow.

Or studio can have it's own workflow without subscribing to any release processes. 🤔

**Comment by derberg** [comment]
> Or studio can have it's own workflow without subscribing to any release processes.

exactly that. Now release workflows are not pushed everywhere, but only to repos with specific topics. So just make sure these topics are not there and remove the workflows you do not need. If you want to have a custom release workflow, good luck 😃 I recommend to stick to `semantic-release` but probably with different configuration in place
