### ISSUE TITLE
Make sure automated bumps ignore `spec` and `bindings` repos

### ISSUE THREAD

**Issue by derberg** [asyncapi/.github#264]
in bump workflow:
- add `spec` and `bindings` as comma separated repos
- remove `html-template`

https://github.com/asyncapi/.github/blob/master/.github/workflows/bump.yml#L34

This is due to make sure no releases take place in these repos just because they have some testing scripts, no real packages to release

details: https://asyncapi.slack.com/archives/C0230UAM6R3/p1702471398660389

**Comment by ankur0904** [comment]
@derberg Can I make the PR?
