### ISSUE TITLE
[BUG] Request a review could ignore bot

### ISSUE THREAD

**Issue by utnim2** [asyncapi/.github#286]
### Describe the bug.

When a pull request is opened we need to remove request review from bot 

like in [generator/#1177](https://github.com/asyncapi/generator/pull/1177)

### Expected behavior

It should not call bot for a review

### Screenshots

![image](https://github.com/asyncapi/.github/assets/127925465/f18aa1ab-44c7-4f47-b692-ff78b6ddf65a)

### How to Reproduce

By opening a PR in the org

### 🥦 Browser

None

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by derberg** [comment]
I don't think we have technical power over that integration. GH does it automatically by extracting info from CODEOWNERS
