### ISSUE TITLE
Rename of package & name space

### ISSUE THREAD

**Issue by thompson-tomo** [asyncapi/.github#290]
### Why do we need this improvement?

Allows for clear ownership of the project

### How will this change help?

Allows clear ownership and easier for user to find

### How could it be implemented/designed?

Tbd

### 🚧 Breaking changes

Yes

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue?

Yes I am willing to submit a PR!

**Comment by derberg** [comment]
@thompson-tomo hey, thanks for submitting the issue but to be honest I have a hard time to understand what it is related to 🤔 what package?

**Comment by thompson-tomo** [comment]
@derberg What happened was I tried to create an issue for Saunter and it ended up in this project. This is why I closed this issue and opened one directly in the Saunter project

**Comment by derberg** [comment]
ok, makes sense, cheers
