### ISSUE TITLE
CONTRIBUTING file should be repository neutral

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/.github#39]
#### Describe the bug
Since the [CONTRIBUTING.md](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md) file is starting to get referenced in multiple repositories it no longer makes sense that the guidelines are tuned towards the [main repository](github.com/asyncapi/asyncapi). 

#### Expected behavior
Expected the guidelines to be repository neutral i.e. not include a link to https://github.com/asyncapi/asyncapi/issues/new under opening issues.

I have not screened the entire document, just noticed https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md#issues

**Comment by derberg** [comment]
Still valid 😓
