### ISSUE TITLE
Automate Sonarcloud project creation

### ISSUE THREAD

**Issue by smoya** [asyncapi/.github#49]
### Reason/Context
Sonarcloud does not create automatically a project on their side whenever we create a GH repository. That means the process is manual and creating them (via https://sonarcloud.io/projects/create) requires ADMIN permission.

### Description
Sonarcloud Projects can be created through their UI or rather API as shown [here](https://sonarcloud.io/web_api/api/projects/create).
That opens the possibility to add some automation around Sonarcloud projects creation through a GH workflow, which will have permissions for doing so.

So far I can see two options for triggering the workflow:

1. Listening to Github Organization Events:
    - Not sure if there is an event dispatched when a new repository is created. If there is, we could just dispatch 
2. Manual trigger whenever we create a new repository.

**Comment by derberg** [comment]
still needed, just no time to do it

**Comment by smoya** [comment]
> still needed, just no time to do it

I would say still the same situation cc @derberg

**Comment by smoya** [comment]
Let's give it another chance
