### ISSUE TITLE
Github actions approve changes that have already been merged

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/.github#58]
#### Describe the bug
If you scroll down to the end of https://github.com/asyncapi/fluffy-robot/pull/5 you see that the bot approves the already merged pull requests. Don't think that is intended 🤔 

#### Expected behavior
Did not expect any re-approving of the PR.

**Comment by derberg** [comment]
This is super strange one, not sure if I can find the answer:

Workflow is pretty clear on who is the PR creator where autoapprove triggers -> https://github.com/asyncapi/fluffy-robot/blob/master/.github/workflows/automerge.yml#L29

This is workflow that approved PR -> https://github.com/asyncapi/fluffy-robot/pull/5/checks?check_run_id=2932575518 triggered on `pull_request_target` event. This was triggering commit - d0e71e8 - the last one. 

My theoretical answer, lemme know if you are happy with it.

---
Sometimes jobs are delayed, we are on a free tier, lots of jobs, sticking in the queue will happen from time to time. When job finally started, PR was already merged and last actor was `asyncapi-bot` as it added `released` label. This is why job was not skipped and approval added.

This is a corner case I see happening only after PR merge and release, very rarely and not harmful. So I say we just close the issue. I do not see a scenario when asyncapi bot does something on someones PR before PR merge

**Comment by jonaslagoni** [comment]
I think the theory is correct yea 🙂 

In case we want to "solve" this one could add something like `if: !contains(github.event.pull_request.labels.*.name, 'released')` 😄

**Comment by derberg** [comment]
@jonaslagoni no opinion here, we can add it, we can leave without it, you reported the bug, up to you 😄 not a problem for me in case you want me to add it

**Comment by jonaslagoni** [comment]
I would opt for a more "stable" CI system that does not confuse users of it, so think we should add it @derberg. Let me know if I need to do anything 🙂

**Comment by derberg** [comment]
> I would opt for a more "stable" CI system that does not confuse users of it

very good point sir!

>  Let me know if I need to do anything 🙂

it is enough that you are there 😄 

I'll update https://github.com/asyncapi/.github/pull/66. I know both are not related but we also know how much noise these updates cause in the system, so if it is possible to have just 50 PR instead of 100 I think it is good to have it in one PR 😅
