### ISSUE TITLE
Alot of umerged PRs

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/.github#59]
#### Describe the bug
At the moment with the CI system, it can occur that we are ended up with a lot of unmerged PRs as such:
![billede](https://user-images.githubusercontent.com/13396189/123793577-27fc8080-d8e2-11eb-9121-acad85183282.png)

#### How to Reproduce
I have no idea, it happens from time to time 😄 

#### Expected behavior
I would expect the CI system to handle this semi-automatically or give us notice of unmerged PR's as it does in some cases but not all.

**Comment by derberg** [comment]
@jonaslagoni for now no idea what is the reason, we need more logs. Please approve https://github.com/asyncapi/.github/pull/66

**Comment by derberg** [comment]
@jonaslagoni figured out what was wrong, have a look at a pr
