### ISSUE TITLE
[go] golangci-lint version should be inferred from Makefile, latest otherwise

### ISSUE THREAD

**Issue by smoya** [asyncapi/.github#60]
#### Describe the bug
Both local `golangci-lint` binary and the one that runs on CI should be pointing to the same version, which are currently not.

CI script should look to the [Makefile](https://github.com/asyncapi/template-for-go-projects/blob/master/Makefile#L16) in order to see if there is a pinned version and use it, `latest` otherwise.

**Comment by derberg** [comment]
did you have some specific idea in mind on how to do this? read file with grep or something `grep "GOLANGCILINT_VERSION =" Makefile  | cut -d'=' -f2` or rather add a target that echos the variable holding version?

Then of course we can echo it in the way that another step have access to that information

**Comment by derberg** [comment]
@smoya is this one still valid?

**Comment by derberg** [comment]
is it not valid anymore?

**Comment by smoya** [comment]
> is it not valid anymore?

It is. I missed the notification.

**Comment by smoya** [comment]
Still valid.
