### ISSUE TITLE
Automerge should auto merge master

### ISSUE THREAD

**Issue by derberg** [asyncapi/.github#68]
Quite often automerge fails because like [here](https://github.com/asyncapi/generator-filters/pull/50) PR was created, but in the meantime something else was merged and therefore PR was out of sync with master - thus blocked from merging.

https://github.com/asyncapi/.github/blob/master/.github/workflows/automerge.yml workflow needs a step that updates PR to latest master. 

We need integrate something like https://github.com/marketplace/actions/auto-update

**Comment by abxhr** [comment]
I would love to work on this! 🚀

**Comment by derberg** [comment]
Please go ahead and lemme know if ya need help

**Comment by derberg** [comment]
This one is already fixed
