### ISSUE TITLE
Workflow that updates every PR with clear info about conventional commits

### ISSUE THREAD

**Issue by derberg** [asyncapi/.github#70]
Even though we have https://github.com/asyncapi/.github/blob/master/.github/workflows/lint-pr-title.yml, it is not enough. We do validation - great. We put errors in logs - that is nice. Problem is:

- checking logs is not that obvious
- we do not inform clearly what is it all about

I noticed some people are confused. Not everyone reads CONTRIBUTING.md and this is a fact we need to accept 🤷🏼 

Would be awesome to have a global GH Actions workflow that, using our bot, posts a message in the PR containing the explanation we already have in the contribu guide -> https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md#conventional-commits

Here you have an example that publishes a comment in an issue -> https://github.com/asyncapi/shape-up-process/blob/master/.github/workflows/scope-welcome.yml. We need something similar but as a comment under PR, and workflow must react on event `pull_request_target`

**Comment by magicmatatjahu** [comment]
As the title is not related to PR stats like coverage, sonarcloud etc. I would add that ideally the comment should only appear if there is an error in the title, and when someone corrects the title the comment should disappear.

**Comment by derberg** [comment]
yeap, would be nice to display it only if the linting job fails, shouldn't be hard, but removing bot message? this would be tricky and from my point of view it is like `super nice to have but not critical`

**Comment by derberg** [comment]
Resolved with https://github.com/asyncapi/.github/pull/182
