### ISSUE TITLE
docs: create README for AsyncAPI org profile

### ISSUE THREAD

**Issue by alequetzalli** [asyncapi/.github#72]
#### Description
Let's create a README for the AsyncAPI organization profile, now that [GH rolled out that new feature](https://github.blog/changelog/2021-09-14-readmes-for-organization-profiles/). It must be visually appealing and we should agree on what is the best to have there. (@derberg thinks one of main things to put there would be all the communication channels.)

**Comment by derberg** [comment]
yay!

I think that we should expose the communication channels we have listed here -> https://github.com/asyncapi/community/issues/1

in general though, it must be an intro, but imho not necessarily intro to AsyncAPI (as a spec) but intro to AsyncAPI Initiative, our goals, purpose, communication, and important links to blog, roadmap.

and I love these to be nice looking, not just text, but if we link to slack, it should be slack badge and others (we can use https://shields.io/)

**Comment by alequetzalli** [comment]
PR is underway! 😄

https://github.com/asyncapi/.github/pull/76

**Comment by alequetzalli** [comment]
Changes are live!!
https://github.com/asyncapi

**Comment by japui-coder** [comment]
docs: create README for AsyncAPI org profile #72
