### ISSUE TITLE
Remove `welcome` workflow and replace with something custom

### ISSUE THREAD

**Issue by derberg** [asyncapi/.github#73]
This workflow https://github.com/asyncapi/.github/blob/master/.github/workflows/welcome-first-time-contrib.yml and the `first-interaction` action that we use it causes headache for the 2nd time

It is failing again on all the workflows, blocking merges and it is closing some serious overload on the GitHub API and therefore rate limit alerts. Not cool at all!

We should remove it (I do not want us to wait for https://github.com/actions/first-interaction/issues/56 and then again in few months face 3rd failure, 2 is enough) and replace with our custom solution:

- we just need to learn from current action how they figure out checking first contributor (now they do a look over all PRs or issues which seems unbelievably harmful for the API -> https://github.com/actions/first-interaction/blob/main/src/main.ts) and do it better, maybe API already allows it, if not rest client, maybe graphql. This workflow is great but not worth it if it is going to cause so many problems in auto merging. We should just push GH for something better, if API is not the answer ATM
- we can have just a custom script like we already do [here](https://github.com/asyncapi/spec/blob/master/.github/workflows/update-spec.yaml#L45-L51), and [here](https://github.com/asyncapi/.github/blob/master/.github/workflows/automerge-orphans.yml) is some example on how to talk graphql-ish

**Comment by KhudaDad414** [comment]
Did some digging In Github Graphql API and it seems that issues search can be greatly optimized using `filterBy` of `IssueConnection`.
But sadly `PullRequestConnection` does not have a `filterBy` argument so I don't know if using the Graphql API will help or not since we have to filter all pull requests using Graphql API as well.

**Comment by KhudaDad414** [comment]
We can't use that. By default, that field is `NONE`. It doesn't change by opening a pull request or reporting an issue. (strange 🤔)
[Tested Here](https://github.com/KhudaDad414/first-interaction)

**Comment by derberg** [comment]
@KhudaDad414 

I just tried this:
```
query { 
  repository(owner: "asyncapi", name: "spec"){
    name
    pullRequests (last: 100){
      edges {
        node {
          url
          authorAssociation
        }
      }
    }
  }
}
```

and got this on the list
```
{
            "node": {
              "url": "https://github.com/asyncapi/spec/pull/613",
              "authorAssociation": "FIRST_TIME_CONTRIBUTOR"
            }
}
```

**Comment by KhudaDad414** [comment]
@derberg
can you take a look at [this repo](https://github.com/KhudaDad414/first-interaction)?
I have figured out how to do that with the first issue but for some reason, `authorAssociation` is always `NONE` for the account that I am using for testing.

**Comment by derberg** [comment]
Damn, when you read docs carefully, looks like it is `commit` related interaction, and because we all work through forks, commit is outside the repo, thus NONE (at least I think so)

<img width="474" alt="Screenshot 2021-10-05 at 10 21 41" src="https://user-images.githubusercontent.com/6995927/135986904-91d2cb6b-eae6-4174-b40f-a1981a1678a0.png">

I see it worked for an issue, but because you count the amount of issues per user, I guess this is the only way to go 🤔
