### ISSUE TITLE
workflows that require `npm install` are long running and sometimes blocking

### ISSUE THREAD

**Issue by derberg** [asyncapi/.github#80]
We test all npm packages on macos, windows and linux. Macos is the slowest and sometimes `npm install` fails. Sometimes you don't really want to wait 15min for a PR test to complete.

Hint:

There are some solutions out there that can be plugged into the workflow to cache npm modules or just reuse some other cache.

**Comment by HollowMan6** [comment]
Hi! Since Setup Node.js workflow v2.4.1 support caching packages dependencies by itself: https://github.com/actions/setup-node/blob/v2.4.1/docs/advanced-usage.md#caching-packages-dependencies , I've just submitted a PR which takes this benefits. Hope this helps.
