### ISSUE TITLE
improve spec details version in README.md 

### ISSUE THREAD

**Issue by iamVP7** [asyncapi/.github#82]
Recently [README.md](https://github.com/asyncapi/.github/blob/master/profile/README.md) is published. In this for Spec details; spec latest version is hardcoded.

#### Reason/Context
Please try answering few of those questions
- Why we need this improvement?
We have to keep track of this file and change spec version each time of release. We will change things at one website router file if one change is introduced.

- How will this change help?
Manual spec version change can be avoided.

- What is the motivation? 
Automatically pointing to latest spec release using [netlify redirect](https://www.asyncapi.com/docs/specifications/latest) which is already in use

#### Description
Please try answering few of those questions
- What changes have to be introduced?
URL will  be changed from https://www.asyncapi.com/docs/specifications/v2.2.0 to https://www.asyncapi.com/docs/specifications/latest

- Will this be a breaking change?
If we remove the netlify router in website repo it will be changed.

Mentor: @alequetzalli

**Comment by alequetzalli** [comment]
You're amazing! Thank you so much for your contribution. ✨
