### ISSUE TITLE
Readme links check

### ISSUE THREAD

**Issue by panwauu** [asyncapi/.github#92]
I found some broken links in .md files and googled if there are tools to report broken tools and found this [github action](https://github.com/gaurav-nelson/github-action-markdown-link-check) and this other [github action](https://github.com/ocular-d/md-linkcheck-action).
It would be nice to have this in all of the repos

**Comment by derberg** [comment]
we should definitely use https://github.com/gaurav-nelson/github-action-markdown-link-check and have 2 workflows:
- 1 to check only modified files on a PR level
- 1 to periodically, cron job, like once a week check all files in a repo, and push notifications in case of failure to our slack, maybe docs channel @alequetzalli ?

**Comment by alequetzalli** [comment]
hey @derberg, that sounds like a great idea and then getting a push notification in the `#docs` Slack channel is incredibly useful!

**Comment by derberg** [comment]
whoever picks up this issue, please remember that workflow must be created in `.github` repo but initially please test it on your own test repo and then provide links in PR so we can check how it worked.

you do not have to test Slack integration, just adapt [the following steps](hub/blob/master/.github/workflows/notify-tsc-members-mention.yml#L41-L52) that we already use for other slack-notification-related workflows. We will provide you with proper webhook secret for `#docs` channel when needed

good luck ☮️

**Comment by Namyalg** [comment]
I would like to work on this issue

**Comment by derberg** [comment]
Please go ahead. Lemme know if you need help. Are you part of OpenForce?

**Comment by Namyalg** [comment]
Yep

**Comment by aniketh-varma** [comment]
Hi, would like to work on this issue. I am a part of OpenForce 2022.

**Comment by derberg** [comment]
@aniketh-varma Hey, thanks but since @Namyalg was here first, the issue belongs to her. Please have a look at other issues from the list.

**Comment by Namyalg** [comment]
As mentioned [here](https://github.com/gaurav-nelson/github-action-markdown-link-check), is there anything specific that should go into the `mlc_config.json` file ?

**Comment by derberg** [comment]
@Namyalg hey, we are having some issues with automation:

- https://github.com/asyncapi/.github/blob/master/.github/workflows/link-check-cron.yml#L31 is a wrong env key, it should be `SLACK_WEBHOOK_URL: ${{ secrets.SLACK_DOCS_CHANNEL }}`
- after looking at https://github.com/asyncapi/spec/runs/5802713025?check_suite_focus=true#step:4:23 sounds like config file is required?

**Comment by Namyalg** [comment]
I will change the name of the `env` variable
The absence of the config file is indicated, but it does not lead to any unexpected behavior

**Comment by derberg** [comment]
I think we will need config to ignore these links:
```
[✖] https://github.com/asyncapi/spec/tree/BRANCH_NAME → Status: 404
[✖] https://github.com/asyncapi/spec-json-schemas/tree/BRANCH_NAME → Status: 404
[✖] https://github.com/asyncapi/parser-js/tree/BRANCH_NAME → Status: 404
[✖] https://github.com/asyncapi/website/pull/PULLREQUEST → Status: 404
```
